### ISSUE TITLE
SignIn

### ISSUE THREAD

**Issue by danilobjr** [OneDevCompany/ajuda-saude-ui#1]
## Tasks
- [ ] Create input component
- [ ] Screen ([Figma - Sprint 1 page](https://www.figma.com/file/E2Rd4Iw8WYE4aknHPKWGFN/Ajuda-Sa%C3%BAde?node-id=1%3A12))
  - Checkbox for _keep me signed in_
  - Link to _forgot password_ screen
- [ ] Validation (check Constraints section for more details)
- [ ] Backend integration

### Constraints
- **Login field**
  - Must be able to receive _Email_, _Phone_ or _CPF_ as input data 
  - Validation should occurs as the image on Attachments section
- **Password field** must have at least:
  - One lowercase letter
  - One uppercase letter
  - One numeric digit

### Attachments
CPF validation logic
![120936779_912265929181271_4453545540929310338_n](https://user-images.githubusercontent.com/735556/95264160-42974280-0805-11eb-9939-65df7cae4c68.png)
